"""Initial migration

Revision ID: 15992ca872e6
Revises: f702197f72cd
Create Date: 2025-06-11 03:52:05.413608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15992ca872e6'
down_revision: Union[str, None] = 'f702197f72cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'info',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'taps',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(op.f('users_social_id_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'social_id')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'registration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('social_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_social_id_key'), 'users', ['social_id'])
    op.alter_column('users', 'taps',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'info',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
